# Generated by Django 3.2.8 on 2021-10-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211019_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnotherClassJustForMe',
        ),
    ]
