# Generated by Django 3.2.8 on 2021-10-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_anotherclassjustforme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
